# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalcForPyQt0.1_ResultShow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(401, 300)
        self.OKButton = QtWidgets.QPushButton(Dialog)
        self.OKButton.setGeometry(QtCore.QRect(210, 250, 75, 23))
        self.OKButton.setObjectName("OKButton")
        self.CancelButton = QtWidgets.QPushButton(Dialog)
        self.CancelButton.setGeometry(QtCore.QRect(310, 250, 75, 23))
        self.CancelButton.setObjectName("CancelButton")
        self.ShowResult = QtWidgets.QPlainTextEdit(Dialog)
        self.ShowResult.setGeometry(QtCore.QRect(140, 80, 104, 71))
        self.ShowResult.setObjectName("ShowResult")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.OKButton.setText(_translate("Dialog", "OK"))
        self.CancelButton.setText(_translate("Dialog", "Cancel"))
