# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalcForPyQt0.1_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AdditionButton = QtWidgets.QPushButton(self.centralwidget)
        self.AdditionButton.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.AdditionButton.setObjectName("AdditionButton")
        self.SubtractionButton = QtWidgets.QPushButton(self.centralwidget)
        self.SubtractionButton.setGeometry(QtCore.QRect(110, 20, 81, 23))
        self.SubtractionButton.setObjectName("SubtractionButton")
        self.MultiplicationButton = QtWidgets.QPushButton(self.centralwidget)
        self.MultiplicationButton.setGeometry(QtCore.QRect(210, 20, 101, 23))
        self.MultiplicationButton.setObjectName("MultiplicationButton")
        self.DivisionButton = QtWidgets.QPushButton(self.centralwidget)
        self.DivisionButton.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.DivisionButton.setObjectName("DivisionButton")
        self.ExponentiationButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExponentiationButton.setGeometry(QtCore.QRect(410, 20, 101, 23))
        self.ExponentiationButton.setObjectName("ExponentiationButton")
        self.RadicalButton = QtWidgets.QPushButton(self.centralwidget)
        self.RadicalButton.setGeometry(QtCore.QRect(530, 20, 71, 23))
        self.RadicalButton.setObjectName("RadicalButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AdditionButton.setText(_translate("MainWindow", "Addition"))
        self.SubtractionButton.setText(_translate("MainWindow", "Subtraction"))
        self.MultiplicationButton.setText(_translate("MainWindow", "Multiplication"))
        self.DivisionButton.setText(_translate("MainWindow", "Division"))
        self.ExponentiationButton.setText(_translate("MainWindow", "Exponentiation"))
        self.RadicalButton.setText(_translate("MainWindow", "Radical"))
