# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalcAlpha0.3ForPyQt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(100, 240, 201, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.AdditionButton = QtWidgets.QPushButton(Dialog)
        self.AdditionButton.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.AdditionButton.setObjectName("AdditionButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Welcome to use CalcAlpha0.3!"))
        self.AdditionButton.setText(_translate("Dialog", "Addition"))
