# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalcForPyQt0.1_AdditionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.GetResultButton = QtWidgets.QPushButton(Dialog)
        self.GetResultButton.setGeometry(QtCore.QRect(150, 190, 91, 31))
        self.GetResultButton.setObjectName("GetResultButton")
        self.Adder1TE = QtWidgets.QTextEdit(Dialog)
        self.Adder1TE.setGeometry(QtCore.QRect(30, 30, 104, 71))
        self.Adder1TE.setObjectName("Adder1TE")
        self.Adder1PT = QtWidgets.QPlainTextEdit(Dialog)
        self.Adder1PT.setGeometry(QtCore.QRect(30, 120, 71, 31))
        self.Adder1PT.setObjectName("Adder1PT")
        self.Adder2PT = QtWidgets.QPlainTextEdit(Dialog)
        self.Adder2PT.setGeometry(QtCore.QRect(290, 120, 71, 31))
        self.Adder2PT.setObjectName("Adder2PT")
        self.Adder2TE = QtWidgets.QTextEdit(Dialog)
        self.Adder2TE.setGeometry(QtCore.QRect(260, 30, 104, 71))
        self.Adder2TE.setObjectName("Adder2TE")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.GetResultButton.setText(_translate("Dialog", "Get Result!"))
        self.Adder1PT.setPlainText(_translate("Dialog", "Adder 1"))
        self.Adder2PT.setPlainText(_translate("Dialog", "Adder 2"))
